from app.database import SessionLocal
from app.models import Drug

drugs_data = [
    {
        "name": "Paracetamol 500mg",
        "generic_name": "Paracetamol",
        "category": "Analgesik & Antipiretik",
        "description": "Obat penurun panas dan pereda nyeri. Digunakan untuk demam, sakit kepala, dan nyeri ringan.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Amoxicillin 500mg",
        "generic_name": "Amoxicillin",
        "category": "Antibiotik",
        "description": "Antibiotik golongan penisilin untuk infeksi bakteri seperti ISPA, infeksi saluran kemih, dan kulit.",
        "dosage_form": "Kapsul",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "Omeprazole 20mg",
        "generic_name": "Omeprazole",
        "category": "Antasida & PPI",
        "description": "Penghambat pompa proton untuk mengatasi maag, GERD, dan tukak lambung.",
        "dosage_form": "Kapsul",
        "manufacturer": "Pharos",
    },
    {
        "name": "Cetirizine 10mg",
        "generic_name": "Cetirizine",
        "category": "Antihistamin",
        "description": "Antihistamin untuk alergi seperti pilek, bersin-bersin, dan gatal-gatal.",
        "dosage_form": "Tablet",
        "manufacturer": "Dexa Medica",
    },
    {
        "name": "Metformin 500mg",
        "generic_name": "Metformin HCl",
        "category": "Antidiabetes",
        "description": "Obat untuk mengontrol kadar gula darah pada pasien diabetes tipe 2.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Amlodipine 5mg",
        "generic_name": "Amlodipine Besylate",
        "category": "Antihypertensi",
        "description": "Obat untuk menurunkan tekanan darah tinggi dan mengatasi angina.",
        "dosage_form": "Tablet",
        "manufacturer": "Novell Pharmaceutical",
    },
    {
        "name": "Salbutamol 4mg",
        "generic_name": "Salbutamol",
        "category": "Bronkodilator",
        "description": "Obat untuk meredakan gejala asma dan penyakit paru obstruktif kronis (PPOK).",
        "dosage_form": "Tablet",
        "manufacturer": "GlaxoSmithKline",
    },
    {
        "name": "Ibuprofen 400mg",
        "generic_name": "Ibuprofen",
        "category": "NSAID",
        "description": "Obat antiinflamasi nonsteroid untuk pereda nyeri dan antiinflamasi.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "ORS sachet",
        "generic_name": "Oral Rehydration Salts",
        "category": "Elektrolit",
        "description": "Serbuk untuk cairan rehidrasi oral, mengatasi diare dan dehidrasi.",
        "dosage_form": "Serbuk",
        "manufacturer": "Various",
    },
    {
        "name": "Vitamin C 1000mg",
        "generic_name": "Asam Askorbat",
        "category": "Suplemen",
        "description": "Suplemen vitamin C untuk daya tahan tubuh dan antioksidan.",
        "dosage_form": "Tablet hisap",
        "manufacturer": "Youvit",
    },
    {
        "name": "Loratadine 10mg",
        "generic_name": "Loratadine",
        "category": "Antihistamin",
        "description": "Antihistamin non-mengantuk untuk membantu meredakan gejala alergi dan biduran.",
        "dosage_form": "Tablet",
        "manufacturer": "Novell Pharmaceutical",
    },
    {
        "name": "Azithromycin 500mg",
        "generic_name": "Azithromycin",
        "category": "Antibiotik",
        "description": "Antibiotik makrolida untuk infeksi bakteri tertentu sesuai resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Pharos",
    },
    {
        "name": "Dexamethasone 0.5mg",
        "generic_name": "Dexamethasone",
        "category": "Kortikosteroid",
        "description": "Kortikosteroid untuk kondisi peradangan dan alergi tertentu berdasarkan resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Losartan 50mg",
        "generic_name": "Losartan Potassium",
        "category": "Antihipertensi",
        "description": "Obat golongan ARB untuk membantu mengontrol tekanan darah tinggi.",
        "dosage_form": "Tablet",
        "manufacturer": "Kalbe Farma",
    },
    {
        "name": "Valsartan 80mg",
        "generic_name": "Valsartan",
        "category": "Antihipertensi",
        "description": "Obat untuk tekanan darah tinggi dan kondisi jantung tertentu sesuai arahan dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Novartis",
    },
    {
        "name": "Atorvastatin 20mg",
        "generic_name": "Atorvastatin Calcium",
        "category": "Penurun Kolesterol",
        "description": "Statin untuk membantu menurunkan kadar kolesterol dan risiko penyakit kardiovaskular.",
        "dosage_form": "Tablet",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Simvastatin 20mg",
        "generic_name": "Simvastatin",
        "category": "Penurun Kolesterol",
        "description": "Obat penurun kolesterol yang digunakan bersama pengaturan pola makan.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Glimepiride 2mg",
        "generic_name": "Glimepiride",
        "category": "Antidiabetes",
        "description": "Obat antidiabetes oral untuk membantu mengontrol gula darah pada diabetes tipe 2.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "Furosemide 40mg",
        "generic_name": "Furosemide",
        "category": "Diuretik",
        "description": "Obat pelancar urin untuk membantu mengurangi kelebihan cairan dalam kondisi tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Indofarma",
    },
    {
        "name": "Domperidone 10mg",
        "generic_name": "Domperidone",
        "category": "Antiemetik",
        "description": "Obat untuk membantu meredakan mual dan muntah sesuai anjuran tenaga kesehatan.",
        "dosage_form": "Tablet",
        "manufacturer": "Pyridam",
    },
    {
        "name": "Loperamide 2mg",
        "generic_name": "Loperamide HCl",
        "category": "Antidiare",
        "description": "Obat untuk membantu mengurangi frekuensi buang air besar pada diare akut tertentu.",
        "dosage_form": "Kapsul",
        "manufacturer": "Imodium",
    },
    {
        "name": "Antasida DOEN",
        "generic_name": "Aluminium Hydroxide dan Magnesium Hydroxide",
        "category": "Antasida",
        "description": "Obat untuk menetralkan asam lambung dan membantu meredakan gejala maag.",
        "dosage_form": "Suspensi",
        "manufacturer": "Generik",
    },
    {
        "name": "Zinc 20mg",
        "generic_name": "Zinc Sulfate",
        "category": "Suplemen",
        "description": "Suplemen zinc yang umum digunakan sebagai pendamping penanganan diare pada anak.",
        "dosage_form": "Tablet dispersibel",
        "manufacturer": "Generik",
    },
    {
        "name": "Clopidogrel 75mg",
        "generic_name": "Clopidogrel",
        "category": "Antiplatelet",
        "description": "Obat antiplatelet untuk membantu mencegah pembentukan bekuan darah berdasarkan resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Miconazole 2% cream",
        "generic_name": "Miconazole Nitrate",
        "category": "Antijamur",
        "description": "Krim antijamur untuk membantu mengatasi infeksi jamur pada kulit.",
        "dosage_form": "Krim topikal",
        "manufacturer": "Daktarin",
    },
    {
        "name": "Cefixime 200mg",
        "generic_name": "Cefixime",
        "category": "Antibiotik",
        "description": "Antibiotik sefalosporin untuk infeksi bakteri tertentu sesuai resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Dexa Medica",
    },
    {
        "name": "Ciprofloxacin 500mg",
        "generic_name": "Ciprofloxacin",
        "category": "Antibiotik",
        "description": "Antibiotik kuinolon untuk infeksi bakteri tertentu dan harus digunakan sesuai resep.",
        "dosage_form": "Tablet",
        "manufacturer": "Bernofarm",
    },
    {
        "name": "Ranitidine 150mg",
        "generic_name": "Ranitidine",
        "category": "Antagonis H2",
        "description": "Obat penurun produksi asam lambung untuk keluhan maag tertentu sesuai arahan tenaga kesehatan.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Lansoprazole 30mg",
        "generic_name": "Lansoprazole",
        "category": "Antasida & PPI",
        "description": "Penghambat pompa proton untuk membantu menangani GERD dan tukak lambung.",
        "dosage_form": "Kapsul",
        "manufacturer": "Kalbe Farma",
    },
    {
        "name": "Nifedipine 10mg",
        "generic_name": "Nifedipine",
        "category": "Antihipertensi",
        "description": "Obat calcium channel blocker untuk tekanan darah tinggi dan kondisi jantung tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Bisoprolol 5mg",
        "generic_name": "Bisoprolol Fumarate",
        "category": "Antihipertensi",
        "description": "Beta blocker untuk membantu mengontrol tekanan darah dan denyut jantung sesuai resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Merck",
    },
    {
        "name": "Spironolactone 25mg",
        "generic_name": "Spironolactone",
        "category": "Diuretik",
        "description": "Diuretik hemat kalium untuk kondisi kelebihan cairan atau tekanan darah tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Pratapa Nirmala",
    },
    {
        "name": "Allopurinol 100mg",
        "generic_name": "Allopurinol",
        "category": "Antigout",
        "description": "Obat untuk membantu menurunkan kadar asam urat pada kondisi gout kronis.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Colchicine 0.5mg",
        "generic_name": "Colchicine",
        "category": "Antigout",
        "description": "Obat untuk serangan gout akut dan pencegahan tertentu sesuai petunjuk dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Ambroxol 30mg",
        "generic_name": "Ambroxol HCl",
        "category": "Mukolitik",
        "description": "Obat pengencer dahak untuk membantu meredakan batuk berdahak.",
        "dosage_form": "Tablet",
        "manufacturer": "Erela",
    },
    {
        "name": "Guaifenesin 100mg/5ml",
        "generic_name": "Guaifenesin",
        "category": "Ekspektoran",
        "description": "Sirup ekspektoran untuk membantu mengeluarkan dahak pada batuk produktif.",
        "dosage_form": "Sirup",
        "manufacturer": "Generik",
    },
    {
        "name": "Chlorpheniramine 4mg",
        "generic_name": "Chlorpheniramine Maleate",
        "category": "Antihistamin",
        "description": "Antihistamin untuk gejala alergi yang dapat menyebabkan kantuk.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Hydrocortisone 1% cream",
        "generic_name": "Hydrocortisone",
        "category": "Kortikosteroid",
        "description": "Krim kortikosteroid ringan untuk membantu meredakan gatal dan peradangan kulit tertentu.",
        "dosage_form": "Krim topikal",
        "manufacturer": "Generik",
    },
    {
        "name": "Povidone Iodine 10%",
        "generic_name": "Povidone Iodine",
        "category": "Antiseptik",
        "description": "Antiseptik luar untuk membersihkan luka ringan dan area kulit.",
        "dosage_form": "Larutan topikal",
        "manufacturer": "Betadine",
    },
    {
        "name": "Ferrous Sulfate 200mg",
        "generic_name": "Ferrous Sulfate",
        "category": "Suplemen",
        "description": "Suplemen zat besi untuk membantu menangani atau mencegah kekurangan zat besi.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Folic Acid 1mg",
        "generic_name": "Asam Folat",
        "category": "Suplemen",
        "description": "Suplemen asam folat untuk kebutuhan nutrisi tertentu, termasuk masa kehamilan sesuai anjuran.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Insulin Glargine 100 IU/ml",
        "generic_name": "Insulin Glargine",
        "category": "Antidiabetes",
        "description": "Insulin kerja panjang untuk membantu mengontrol gula darah sesuai resep dan edukasi tenaga kesehatan.",
        "dosage_form": "Injeksi",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Fluconazole 150mg",
        "generic_name": "Fluconazole",
        "category": "Antijamur",
        "description": "Antijamur sistemik untuk infeksi jamur tertentu sesuai resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Acyclovir 400mg",
        "generic_name": "Acyclovir",
        "category": "Antivirus",
        "description": "Antivirus untuk infeksi herpes tertentu sesuai arahan dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Oseltamivir 75mg",
        "generic_name": "Oseltamivir",
        "category": "Antivirus",
        "description": "Antivirus untuk influenza tertentu bila digunakan sesuai waktu dan resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Roche",
    },
]


def seed():
    db = SessionLocal()
    try:
        existing_names = {name for (name,) in db.query(Drug.name).all()}
        added = 0
        for data in drugs_data:
            if data["name"] not in existing_names:
                db.add(Drug(**data))
                added += 1
        db.commit()
        print(f"Berhasil menambahkan {added} data obat baru.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
