from app.database import SessionLocal
from app.models import Drug

CATEGORY_IMAGES = {
    "Analgesik & Antipiretik": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antibiotik": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    "Antasida & PPI": "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400",
    "Antihistamin": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antidiabetes": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400",
    "Antihypertensi": "https://images.unsplash.com/photo-1576091160557-1b3e6b3d6e3a?w=400",
    "Bronkodilator": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400",
    "NSAID": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Elektrolit": "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=400",
    "Suplemen": "https://images.unsplash.com/photo-1607619056574-7b8d2ee536b2?w=400",
    "Kortikosteroid": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Penurun Kolesterol": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400",
    "Diuretik": "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400",
    "Antiemetik": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antidiare": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antijamur": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antivirus": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    "Antiplatelet": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400",
    "Antigout": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Mukolitik": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Ekspektoran": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "Antiseptik": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
}
DEFAULT_IMAGE = "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400"

def get_image_for_category(category: str | None) -> str:
    return CATEGORY_IMAGES.get(category or "", DEFAULT_IMAGE)

drugs_data = [
    {
        "name": "Paracetamol 500mg",
        "generic_name": "Paracetamol",
        "category": "Analgesik & Antipiretik",
        "description": "Obat penurun panas dan pereda nyeri. Digunakan untuk demam, sakit kepala, dan nyeri ringan.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Amoxicillin 500mg",
        "generic_name": "Amoxicillin",
        "category": "Antibiotik",
        "description": "Antibiotik golongan penisilin untuk infeksi bakteri seperti ISPA, infeksi saluran kemih, dan kulit.",
        "dosage_form": "Kapsul",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "Omeprazole 20mg",
        "generic_name": "Omeprazole",
        "category": "Antasida & PPI",
        "description": "Penghambat pompa proton untuk mengatasi maag, GERD, dan tukak lambung.",
        "dosage_form": "Kapsul",
        "manufacturer": "Pharos",
    },
    {
        "name": "Cetirizine 10mg",
        "generic_name": "Cetirizine",
        "category": "Antihistamin",
        "description": "Antihistamin untuk alergi seperti pilek, bersin-bersin, dan gatal-gatal.",
        "dosage_form": "Tablet",
        "manufacturer": "Dexa Medica",
    },
    {
        "name": "Metformin 500mg",
        "generic_name": "Metformin HCl",
        "category": "Antidiabetes",
        "description": "Obat untuk mengontrol kadar gula darah pada pasien diabetes tipe 2.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Amlodipine 5mg",
        "generic_name": "Amlodipine Besylate",
        "category": "Antihypertensi",
        "description": "Obat untuk menurunkan tekanan darah tinggi dan mengatasi angina.",
        "dosage_form": "Tablet",
        "manufacturer": "Novell Pharmaceutical",
    },
    {
        "name": "Salbutamol 4mg",
        "generic_name": "Salbutamol",
        "category": "Bronkodilator",
        "description": "Obat untuk meredakan gejala asma dan penyakit paru obstruktif kronis (PPOK).",
        "dosage_form": "Tablet",
        "manufacturer": "GlaxoSmithKline",
    },
    {
        "name": "Ibuprofen 400mg",
        "generic_name": "Ibuprofen",
        "category": "NSAID",
        "description": "Obat antiinflamasi nonsteroid untuk pereda nyeri dan antiinflamasi.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "ORS sachet",
        "generic_name": "Oral Rehydration Salts",
        "category": "Elektrolit",
        "description": "Serbuk untuk cairan rehidrasi oral, mengatasi diare dan dehidrasi.",
        "dosage_form": "Serbuk",
        "manufacturer": "Various",
    },
    {
        "name": "Vitamin C 1000mg",
        "generic_name": "Asam Askorbat",
        "category": "Suplemen",
        "description": "Suplemen vitamin C untuk daya tahan tubuh dan antioksidan.",
        "dosage_form": "Tablet hisap",
        "manufacturer": "Youvit",
    },
    {
        "name": "Loratadine 10mg",
        "generic_name": "Loratadine",
        "category": "Antihistamin",
        "description": "Antihistamin non-mengantuk untuk membantu meredakan gejala alergi dan biduran.",
        "dosage_form": "Tablet",
        "manufacturer": "Novell Pharmaceutical",
    },
    {
        "name": "Azithromycin 500mg",
        "generic_name": "Azithromycin",
        "category": "Antibiotik",
        "description": "Antibiotik makrolida untuk infeksi bakteri tertentu sesuai resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Pharos",
    },
    {
        "name": "Dexamethasone 0.5mg",
        "generic_name": "Dexamethasone",
        "category": "Kortikosteroid",
        "description": "Kortikosteroid untuk kondisi peradangan dan alergi tertentu berdasarkan resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Losartan 50mg",
        "generic_name": "Losartan Potassium",
        "category": "Antihipertensi",
        "description": "Obat golongan ARB untuk membantu mengontrol tekanan darah tinggi.",
        "dosage_form": "Tablet",
        "manufacturer": "Kalbe Farma",
    },
    {
        "name": "Valsartan 80mg",
        "generic_name": "Valsartan",
        "category": "Antihipertensi",
        "description": "Obat untuk tekanan darah tinggi dan kondisi jantung tertentu sesuai arahan dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Novartis",
    },
    {
        "name": "Atorvastatin 20mg",
        "generic_name": "Atorvastatin Calcium",
        "category": "Penurun Kolesterol",
        "description": "Statin untuk membantu menurunkan kadar kolesterol dan risiko penyakit kardiovaskular.",
        "dosage_form": "Tablet",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Simvastatin 20mg",
        "generic_name": "Simvastatin",
        "category": "Penurun Kolesterol",
        "description": "Obat penurun kolesterol yang digunakan bersama pengaturan pola makan.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Glimepiride 2mg",
        "generic_name": "Glimepiride",
        "category": "Antidiabetes",
        "description": "Obat antidiabetes oral untuk membantu mengontrol gula darah pada diabetes tipe 2.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "Furosemide 40mg",
        "generic_name": "Furosemide",
        "category": "Diuretik",
        "description": "Obat pelancar urin untuk membantu mengurangi kelebihan cairan dalam kondisi tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Indofarma",
    },
    {
        "name": "Domperidone 10mg",
        "generic_name": "Domperidone",
        "category": "Antiemetik",
        "description": "Obat untuk membantu meredakan mual dan muntah sesuai anjuran tenaga kesehatan.",
        "dosage_form": "Tablet",
        "manufacturer": "Pyridam",
    },
    {
        "name": "Loperamide 2mg",
        "generic_name": "Loperamide HCl",
        "category": "Antidiare",
        "description": "Obat untuk membantu mengurangi frekuensi buang air besar pada diare akut tertentu.",
        "dosage_form": "Kapsul",
        "manufacturer": "Imodium",
    },
    {
        "name": "Antasida DOEN",
        "generic_name": "Aluminium Hydroxide dan Magnesium Hydroxide",
        "category": "Antasida",
        "description": "Obat untuk menetralkan asam lambung dan membantu meredakan gejala maag.",
        "dosage_form": "Suspensi",
        "manufacturer": "Generik",
    },
    {
        "name": "Zinc 20mg",
        "generic_name": "Zinc Sulfate",
        "category": "Suplemen",
        "description": "Suplemen zinc yang umum digunakan sebagai pendamping penanganan diare pada anak.",
        "dosage_form": "Tablet dispersibel",
        "manufacturer": "Generik",
    },
    {
        "name": "Clopidogrel 75mg",
        "generic_name": "Clopidogrel",
        "category": "Antiplatelet",
        "description": "Obat antiplatelet untuk membantu mencegah pembentukan bekuan darah berdasarkan resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Miconazole 2% cream",
        "generic_name": "Miconazole Nitrate",
        "category": "Antijamur",
        "description": "Krim antijamur untuk membantu mengatasi infeksi jamur pada kulit.",
        "dosage_form": "Krim topikal",
        "manufacturer": "Daktarin",
    },
    {
        "name": "Cefixime 200mg",
        "generic_name": "Cefixime",
        "category": "Antibiotik",
        "description": "Antibiotik sefalosporin untuk infeksi bakteri tertentu sesuai resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Dexa Medica",
    },
    {
        "name": "Ciprofloxacin 500mg",
        "generic_name": "Ciprofloxacin",
        "category": "Antibiotik",
        "description": "Antibiotik kuinolon untuk infeksi bakteri tertentu dan harus digunakan sesuai resep.",
        "dosage_form": "Tablet",
        "manufacturer": "Bernofarm",
    },
    {
        "name": "Ranitidine 150mg",
        "generic_name": "Ranitidine",
        "category": "Antagonis H2",
        "description": "Obat penurun produksi asam lambung untuk keluhan maag tertentu sesuai arahan tenaga kesehatan.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Lansoprazole 30mg",
        "generic_name": "Lansoprazole",
        "category": "Antasida & PPI",
        "description": "Penghambat pompa proton untuk membantu menangani GERD dan tukak lambung.",
        "dosage_form": "Kapsul",
        "manufacturer": "Kalbe Farma",
    },
    {
        "name": "Nifedipine 10mg",
        "generic_name": "Nifedipine",
        "category": "Antihipertensi",
        "description": "Obat calcium channel blocker untuk tekanan darah tinggi dan kondisi jantung tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Bisoprolol 5mg",
        "generic_name": "Bisoprolol Fumarate",
        "category": "Antihipertensi",
        "description": "Beta blocker untuk membantu mengontrol tekanan darah dan denyut jantung sesuai resep dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Merck",
    },
    {
        "name": "Spironolactone 25mg",
        "generic_name": "Spironolactone",
        "category": "Diuretik",
        "description": "Diuretik hemat kalium untuk kondisi kelebihan cairan atau tekanan darah tertentu.",
        "dosage_form": "Tablet",
        "manufacturer": "Pratapa Nirmala",
    },
    {
        "name": "Allopurinol 100mg",
        "generic_name": "Allopurinol",
        "category": "Antigout",
        "description": "Obat untuk membantu menurunkan kadar asam urat pada kondisi gout kronis.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Colchicine 0.5mg",
        "generic_name": "Colchicine",
        "category": "Antigout",
        "description": "Obat untuk serangan gout akut dan pencegahan tertentu sesuai petunjuk dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Ambroxol 30mg",
        "generic_name": "Ambroxol HCl",
        "category": "Mukolitik",
        "description": "Obat pengencer dahak untuk membantu meredakan batuk berdahak.",
        "dosage_form": "Tablet",
        "manufacturer": "Erela",
    },
    {
        "name": "Guaifenesin 100mg/5ml",
        "generic_name": "Guaifenesin",
        "category": "Ekspektoran",
        "description": "Sirup ekspektoran untuk membantu mengeluarkan dahak pada batuk produktif.",
        "dosage_form": "Sirup",
        "manufacturer": "Generik",
    },
    {
        "name": "Chlorpheniramine 4mg",
        "generic_name": "Chlorpheniramine Maleate",
        "category": "Antihistamin",
        "description": "Antihistamin untuk gejala alergi yang dapat menyebabkan kantuk.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Hydrocortisone 1% cream",
        "generic_name": "Hydrocortisone",
        "category": "Kortikosteroid",
        "description": "Krim kortikosteroid ringan untuk membantu meredakan gatal dan peradangan kulit tertentu.",
        "dosage_form": "Krim topikal",
        "manufacturer": "Generik",
    },
    {
        "name": "Povidone Iodine 10%",
        "generic_name": "Povidone Iodine",
        "category": "Antiseptik",
        "description": "Antiseptik luar untuk membersihkan luka ringan dan area kulit.",
        "dosage_form": "Larutan topikal",
        "manufacturer": "Betadine",
    },
    {
        "name": "Ferrous Sulfate 200mg",
        "generic_name": "Ferrous Sulfate",
        "category": "Suplemen",
        "description": "Suplemen zat besi untuk membantu menangani atau mencegah kekurangan zat besi.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Folic Acid 1mg",
        "generic_name": "Asam Folat",
        "category": "Suplemen",
        "description": "Suplemen asam folat untuk kebutuhan nutrisi tertentu, termasuk masa kehamilan sesuai anjuran.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Insulin Glargine 100 IU/ml",
        "generic_name": "Insulin Glargine",
        "category": "Antidiabetes",
        "description": "Insulin kerja panjang untuk membantu mengontrol gula darah sesuai resep dan edukasi tenaga kesehatan.",
        "dosage_form": "Injeksi",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Fluconazole 150mg",
        "generic_name": "Fluconazole",
        "category": "Antijamur",
        "description": "Antijamur sistemik untuk infeksi jamur tertentu sesuai resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Acyclovir 400mg",
        "generic_name": "Acyclovir",
        "category": "Antivirus",
        "description": "Antivirus untuk infeksi herpes tertentu sesuai arahan dokter.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Oseltamivir 75mg",
        "generic_name": "Oseltamivir",
        "category": "Antivirus",
        "description": "Antivirus untuk influenza tertentu bila digunakan sesuai waktu dan resep dokter.",
        "dosage_form": "Kapsul",
        "manufacturer": "Roche",
    },
]


def seed():
    db = SessionLocal()
    try:
        existing_names = {name for (name,) in db.query(Drug.name).all()}
        added = 0
        for data in drugs_data:
            if data["name"] not in existing_names:
                db.add(Drug(**data))
                added += 1
        db.commit()
        print(f"Berhasil menambahkan {added} data obat baru.")
    finally:
        db.close()


# New drugs not in original seed
NEW_DRUGS = [
    {
        "name": "Omeprazole 40mg",
        "generic_name": "Omeprazole",
        "category": "Antasida & PPI",
        "description": "Dosis tinggi penghambat pompa proton untuk kasus maag berat.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Ceftriaxxon 1g",
        "generic_name": "Ceftriaxxon",
        "category": "Antibiotik",
        "description": "Antibiotik cephalosporin IV untuk infeksi bakteri paran.",
        "dosage_form": "Kapsul",
        "manufacturer": "Novartis",
    },
    {
        "name": "Prednisone 5mg",
        "generic_name": "Prednisone",
        "category": "Kortikosteroid",
        "description": "Kortikosteroid oral untuk inflammation dan alergi.",
        "dosage_form": "Tablet",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Montelukast 10mg",
        "generic_name": "Montelukast",
        "category": "Bronkodilator",
        "description": "Leukotrien receptor antagonist untuk asthma dan alergi.",
        "dosage_form": "Tablet",
        "manufacturer": "MSD",
    },
    {
        "name": "Salmeterol 50mcg",
        "generic_name": "Salmeterol",
        "category": "Bronkodilator",
        "description": "Long-acting bronchodilator untuk COPD maintenance.",
        "dosage_form": "Inhaler",
        "manufacturer": "GlaxoSmithKline",
    },
    {
        "name": "Ipratropium 20mcg",
        "generic_name": "Ipratropium",
        "category": "Bronkodilator",
        "description": "Bronchodilator untuk asthma dan COPD, sering dikombinasi dengan salmeterol.",
        "dosage_form": "Inhaler",
        "manufacturer": "Boehringer Ingelheim",
    },
    {
        "name": "Terbutaline 2.5mg",
        "generic_name": "Terbutaline",
        "category": "Bronkodilator",
        "description": "Bronchodilator worka untuk asthma acute.",
        "dosage_form": "Tablet",
        "manufacturer": "Eli Lilly",
    },
    {
        "name": "Amlodipine 10mg",
        "generic_name": "Amlodipine",
        "category": "Antihipertensi",
        "description": "Dosis tinggi antihipertensi calcium channel blocker.",
        "dosage_form": "Tablet",
        "manufacturer": "Novartis",
    },
    {
        "name": "Losartan HCTZ 100/25mg",
        "generic_name": "Losartan Potassium & Hydrochlorothiazide",
        "category": "Antihipertensi",
        "description": "Combination antihipertensi ARB + diuretik.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Metformin XR 500mg",
        "generic_name": "Metformin HCl ER",
        "category": "Antidiabetes",
        "description": "Extended release metformin untuk kontrol gula berkebiasaan.",
        "dosage_form": "Tablet",
        "manufacturer": "Kimia Farma",
    },
    {
        "name": "Glipizide 5mg",
        "generic_name": "Glipizide",
        "category": "Antidiabetes",
        "description": "Sulfonylurea untuk stimulasi insulin secreti.",
        "dosage_form": "Tablet",
        "manufacturer": "Sanbe Farma",
    },
    {
        "name": "Insulin NPH 100 IU/ml",
        "generic_name": "Insulin Isophane",
        "category": "Antidiabetes",
        "description": "Insulin kerja menengah untuk kontrol gula malam hari.",
        "dosage_form": "Injeksi",
        "manufacturer": "Eli Lilly",
    },
    {
        "name": "Warfarin 5mg",
        "generic_name": "Warfarin",
        "category": "Antiklis",
        "description": "Antiklis oral untuk prevensi stroke dan emboli.",
        "dosage_form": "Tablet",
        "manufacturer": "Bayer",
    },
    {
        "name": "Heparin 5000 IU",
        "generic_name": "Heparin",
        "category": "Antiklis",
        "description": "Antiklis IV untuk tindakan medis segera.",
        "dosage_form": "Injeksi",
        "manufacturer": "Sanofi",
    },
    {
        "name": "Rivaroxaban 20mg",
        "generic_name": "Rivaroxaban",
        "category": "Antiklis",
        "description": "Direct oral anticoagulant (DOAC) untuk VTE prevensi.",
        "dosage_form": "Tablet",
        "manufacturer": "Bayer",
    },
    {
        "name": "Dabigatran 150mg",
        "generic_name": "Dabigatran etexilate",
        "category": "Antiklis",
        "description": "Another DOAC untuk prevensi stroke atrial fibrillation.",
        "dosage_form": "Kapsul",
        "manufacturer": "Pfizer",
    },
    {
        "name": "Iron Polysaccharide 30mg",
        "generic_name": "Iron Polysaccharide",
        "category": "Suplemen",
        "description": "Zat besi yang bisa diabsorpsi dengan lebih baik.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Vitamin D3 1000 IU",
        "generic_name": "Colecalciferol",
        "category": "Suplemen",
        "description": "Suplemen vitamin D untuk kekurangan serum vitamin D.",
        "dosage_form": "Tablet",
        "manufacturer": "Youvit",
    },
    {
        "name": "Calcium Carbonate 500mg",
        "generic_name": "Calcium Carbonate",
        "category": "Suplemen",
        "description": "Suplemen kalsium untuk kesehatan tulang dan anti-asam.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Magnesium Oxide 400mg",
        "generic_name": "Magnesium Oxide",
        "category": "Suplemen",
        "description": "Suplemen magnesium untuk kesehammer otot dan nerve function.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Zinc Picolinate 25mg",
        "generic_name": "Zinc Picolinate",
        "category": "Suplemen",
        "description": "Form zinc yang memiliki bioavailabilitas tinggi.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Vitamin B Complex 50mg",
        "generic_name": "Vitamin B Complex",
        "category": "Suplemen",
        "description": "Kompleks vitamin B untuk energi dan sistem saraf.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Vitamin C 500mg",
        "generic_name": "Ascorbic Acid",
        "category": "Suplemen",
        "description": "Dosis tinggi vitamin C untuk daya tahan tubuh.",
        "dosage_form": "Tablet",
        "manufacturer": "Youvit",
    },
    {
        "name": "Chondroitin 600mg",
        "generic_name": "Chondroitin Sulfate",
        "category": "Suplemen",
        "description": "Suplemen untuk kesehatan jalan sirih dan osteoarthrosis.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Glucosamine 500mg",
        "generic_name": "Glucosamine Sulfate",
        "category": "Suplemen",
        "description": "Suplemen untuk reparasi kartilago dan osteoarthritis.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Melatonin 3mg",
        "generic_name": "Melatonin",
        "category": "Suplemen",
        "description": "Hormon untuk menyuikan tidur dan biorhythm.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "L-Lysine 500mg",
        "generic_name": "L-Lysine",
        "category": "Suplemen",
        "description": "Amino asid esensial untuk imunitas dan pemulihan jaringan.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Probiotics 10 billion CFU",
        "generic_name": "Probiotic Blend",
        "category": "Suplemen",
        "description": "Probiotic untuk kesehatan usus dan sistem imun.",
        "dosage_form": "Kapsul",
        "manufacturer": "Generik",
    },
    {
        "name": "Fiber Supplement 5g",
        "generic_name": "Psyllium Husk",
        "category": "Suplemen",
        "description": "Serat diet untuk kesehatan usus dan penurunan kolesterol.",
        "dosage_form": "Serbuk",
        "manufacturer": "Generik",
    },
    {
        "name": "Electrolyte Powder",
        "generic_name": "Electrolyte Mix",
        "category": "Suplemen",
        "description": "Cairan elektrolit untuk dehidrasi dan aktivitas fisik.",
        "dosage_form": "Serbuk",
        "manufacturer": "Generik",
    },
    {
        "name": "Protein Powder Whey 1kg",
        "generic_name": "Whey Protein Isolate",
        "category": "Suplemen",
        "description": "Protein tinggi untuk masa membangun dan pemulihan otot.",
        "dosage_form": "Serbuk",
        "manufacturer": "Generik",
    },
    {
        "name": "Multivitamin Tablet",
        "generic_name": "Multivitamin & Mineral",
        "category": "Suplemen",
        "description": "Kompleks multivitamin sehari-hari untuk kebutuhan nutrisi.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Cough Syrup",
        "generic_name": "Dextromethorphan + Guaifenesin",
        "category": "Ekspektoran",
        "description": "Sirup pereda batuk dengan deksametorfan dan ekspektoran.",
        "dosage_form": "Sirup",
        "manufacturer": "Generik",
    },
    {
        "name": "Cold & Flu Tablet",
        "generic_name": "Paracetamol + Phenylephrine + Chlorpheniramine",
        "category": "Anti-flu",
        "description": "Perpaduan demam penurun, penghalus naph, dan antihistamin untuk flu dan cold.",
        "dosage_form": "Tablet",
        "manufacturer": "Generik",
    },
    {
        "name": "Sore Throat Lozenges",
        "generic_name": "Benzocaine + Menthol",
        "category": "Anti-cough",
        "description": "Tablet cair untuk meredakansakit tenggorokan dan menggugah tenggorokan.",
        "dosage_form": "Lozenge",
        "manufacturer": "Generik",
    },
    {
        "name": "Antacid Suspension 300ml",
        "generic_name": "Magnesium Hydroxide + Aluminium Hydroxide",
        "category": "Antasida",
        "description": "Suspensi anti-asam untuk gejala maag dan refluks.",
        "dosage_form": "Suspensi",
        "manufacturer": "Generik",
    },
    {
        "name": "Oral Rehydration Salts ORS",
        "generic_name": "ORS Powder",
        "category": "Elektrolit",
        "description": "Serbuk ORS untuk dewasa dan anak dalam kondisi dehidrasi.",
        "dosage_form": "Serbuk",
        "manufacturer": "Various",
    },
]

# Append new drugs to existing list
drugs_data.extend(NEW_DRUGS)

USAGE_GUIDES = [
    {
        "match": ["Paracetamol"],
        "indication": "Demam dan nyeri ringan sampai sedang: sakit kepala, nyeri otot, nyeri haid, sakit gigi, dan nyeri setelah cedera.",
        "benefit": "Menurunkan demam dan meredakan nyeri dengan lambung lebih aman dibanding NSAID.",
        "dosage": "Dewasa: 500-1.000 mg per dosis, maksimal 4.000 mg per hari. Anak disesuaikan dengan berat badan.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "3-4x sehari",
    },
    {
        "match": ["Ibuprofen"],
        "indication": "Nyeri dan peradangan: sakit gigi, nyeri haid, sakit kepala, pegal linu, dan nyeri sendi.",
        "benefit": "Meredakan sekaligus mengurangi peradangan, diminum sesudah makan untuk menjaga lambung.",
        "dosage": "Dewasa: 200-400 mg per dosis sesudah makan, maksimal 1.200 mg per hari.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Asam Mefenamat", "Mefenamic Acid"],
        "indication": "Nyeri haid, nyeri otot, nyeri gigi, dan nyeri ringan lainnya.",
        "benefit": "Pereda nyeri dan anti radang yang efektif untuk nyeri haid, maksimal dipakai 5 hari.",
        "dosage": "500 mg per dosis sesudah makan, jangan melebihi 5 hari pemakaian.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Diclofenac"],
        "indication": "Nyeri sendi, nyeri otot, nyeri punggung, dan peradangan pasca cedera.",
        "benefit": "Meredakan nyeri berat dan peradangan pada sistem gerak tubuh.",
        "dosage": "50 mg per dosis sesudah makan, maksimal 150 mg per hari.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Naproxen"],
        "indication": "Nyeri sendi, encok (asam urat), nyeri otot, dan nyeri haid.",
        "benefit": "Khasiatnya panjang sehingga cukup diminum 2 kali sehari.",
        "dosage": "250-500 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Aspirin"],
        "indication": "Pencegahan stroke dan serangan jantung pada pasien berisiko tinggi (dosis rendah).",
        "benefit": "Mencegah penggumpalan darah sehingga aliran darah ke jantung dan otak tetap lancar.",
        "dosage": "100 mg per hari sesudah makan, hanya atas anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Amoxicillin"],
        "indication": "Infeksi bakteri: saluran napas, telinga, kulit, gigi, dan saluran kemih.",
        "benefit": "Membunuh bakteri penyebab infeksi; habiskan seluruh dosis agar bakteri tidak kebal.",
        "dosage": "500 mg per dosis, durasi 7-10 hari sesuai anjuran dokter.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Azitromisin", "Azithromycin"],
        "indication": "Infeksi bakteri saluran napas, tenggorokan, dan kulit.",
        "benefit": "Durasi terapi lebih singkat karena obat bertahan lama di dalam tubuh.",
        "dosage": "500 mg per hari sesudah makan, umumnya 3-5 hari.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Ciprofloxacin"],
        "indication": "Infeksi saluran kemih, infeksi kulit, dan infeksi usus bakteri.",
        "benefit": "Antibiotik spektrum luas untuk infeksi yang tidak merespons antibiotik biasa.",
        "dosage": "500 mg per dosis sesudah makan, umumnya 7-14 hari.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Cefadroxil"],
        "indication": "Infeksi kulit, saluran kemih, dan saluran napas akibat bakteri.",
        "benefit": "Antibiotik sefalosporin yang tersedia dalam bentuk kapsul dan sirup anak.",
        "dosage": "500 mg per dosis, umumnya 7-10 hari.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Metronidazol", "Metronidazole"],
        "indication": "Infeksi bakteri anaerob, amebiasis (disentri), dan giardiasis (mencret parasit).",
        "benefit": "Membunuh parasit dan bakteri anaerob penyebab infeksi usus dan gigi.",
        "dosage": "500 mg per dosis sesudah makan, umumnya 7 hari. Hindari alkohol selama pengobatan.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Omeprazol", "Omeprazole"],
        "indication": "Maag, radang lambung, dan GERD (naiknya asam lambung ke kerongkongan).",
        "benefit": "Menurunkan produksi asam lambung sehingga nyeri dan luka lambung membaik.",
        "dosage": "20 mg per hari, diminum 30 menit sebelum sarapan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Lansoprazol", "Lansoprazole"],
        "indication": "Maag, tukak lambung, dan GERD.",
        "benefit": "Mengurangi asam lambung dengan dosis sekali sehari sebelum makan.",
        "dosage": "30 mg per hari, diminum 30 menit sebelum makan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Pantoprazol", "Pantoprazole"],
        "indication": "Maag dan GERD, termasuk pengobatan jangka panjang.",
        "benefit": "Menstabilkan asam lambung dengan interaksi obat yang minim.",
        "dosage": "40 mg per hari, diminum sebelum makan pagi.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Famotidin", "Famotidine"],
        "indication": "Maag ringan, kembung, dan peningkatan asam lambung.",
        "benefit": "Merilekskan lambung lebih cepat daripada antasida tablet.",
        "dosage": "20 mg per dosis 30 menit sebelum makan.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Antasida", "Hydrotalcite", "Aluminum Hydroxide", "Magnesium Hydroxide"],
        "indication": "Maag ringan, perih lambung, dan kembung setelah makan.",
        "benefit": "Menetralkan asam lambung langsung di tempat, merasa lega dalam hitungan menit.",
        "dosage": "1-2 tablet dikunyah perlahan setelah makan dan sebelum tidur.",
        "usage_time": ["siang", "malam"],
        "frequency": "2-3x sehari",
    },
    {
        "match": ["Domperidon", "Domperidone"],
        "indication": "Mual, muntah, kembung, dan lambung terasa cepat penuh.",
        "benefit": "Membuat lambung kosong lebih cepat sehingga mual mereda.",
        "dosage": "10 mg per dosis 30 menit sebelum makan, maksimal 14 hari.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Ondansetron"],
        "indication": "Mual dan muntah berat, termasuk akibat kemoterapi dan pasca operasi.",
        "benefit": "Menekan refleks mual pada pusat di otak dengan sangat efektif.",
        "dosage": "8 mg per dosis, boleh dihisap/ludah jika bentuk tablet hisap.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "2-3x sehari",
    },
    {
        "match": ["Metoklopramid", "Metoclopramide"],
        "indication": "Mual, muntah, dan kelambatan pengosongan lambung.",
        "benefit": "Mempercepat makanan turun dari lambung ke usus sehingga rasa mual berkurang.",
        "dosage": "10 mg per dosis sesudah makan, maksimal 5 hari dan tidak untuk penggunaan rutin.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Loperamid", "Loperamide"],
        "indication": "Diare akut non-bakteri dan sindrom iritasi usus.",
        "benefit": "Memperlambat gerak usus sehingga tinja lebih padat dan frekuensi mencret berkurang.",
        "dosage": "2 kapsul setelah BAB pertama, lalu 1 kapsul setiap BAB cair; maksimal 8 kapsul per hari.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "Sesuai kebutuhan (hingga 4x sehari)",
    },
    {
        "match": ["Oralit", "ORS", "Elektrolit"],
        "indication": "Pengganti cairan tubuh saat diare atau muntah untuk mencegah dehidrasi.",
        "benefit": "Mengembalikan gula dan garam tubuh sehingga risiko lemas akibat dehidrasi menurun.",
        "dosage": "Larutkan 1 bungkus dalam 1 liter air matang; diminum 200-400 mL per kali mencret.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "Sesuai kebutuhan",
    },
    {
        "match": ["Ambroksol", "Ambroxol"],
        "indication": "Batuk berdahak dan bronkitis dengan dahak yang sulit keluar.",
        "benefit": "Menipiskan dahak sehingga lebih mudah dikeluarkan.",
        "dosage": "30 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Bromheksin", "Bromhexine"],
        "indication": "Batuk berdahak.",
        "benefit": "Melonggarkan dahak supaya batuk lebih produktif.",
        "dosage": "8 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Salbutamol", "Albuterol"],
        "indication": "Asma, sesak napas, dan bronkospasme.",
        "benefit": "Melebarkan saluran napas dalam hitungan menit saat sesak.",
        "dosage": "Tablet: 4 mg per dosis. Inhaler: 1-2 semprotan sesuai kebutuhan.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "Sesuai kebutuhan (hingga 3x sehari)",
    },
    {
        "match": ["Montelukast"],
        "indication": "Pencegahan serangan asma dan gejala alergi musiman.",
        "benefit": "Menjaga saluran napas tetap terbuka bila diminum rutin setiap malam.",
        "dosage": "10 mg per hari untuk dewasa.",
        "usage_time": ["malam"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Cetirizine", "Levocetirizine"],
        "indication": "Alergi: bersin, hidung meler, gatal, dan biduran.",
        "benefit": "Mengurangi gejala alergi sekaligus membantu tidur lebih nyenyak karena bisa menyebabkan kantuk.",
        "dosage": "Cetirizine 10 mg atau Levocetirizine 5 mg per hari.",
        "usage_time": ["malam"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Loratadin", "Loratadine"],
        "indication": "Alergi kulit dan saluran napas: gatal, bersin, dan biduran.",
        "benefit": "Merawat alergi tanpa membuat ngantuk sehingga aman untuk aktivitas siang.",
        "dosage": "10 mg per hari sesudah makan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Klorfeniramin", "Chlorpheniramine"],
        "indication": "Alergi, gatal, bersin, dan pilek alergi.",
        "benefit": "Mengurangi reaksi alergi; dapat menimbulkan kantuk sehingga lebih baik di malam hari.",
        "dosage": "4 mg per dosis.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "2-3x sehari",
    },
    {
        "match": ["Difenhidramin", "Diphenhydramine"],
        "indication": "Alergi dan sulit tidur.",
        "benefit": "Merilekskan tubuh dan membantu cepat tidur.",
        "dosage": "25-50 mg diminum 30 menit sebelum tidur.",
        "usage_time": ["malam"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Deksametason", "Dexamethasone"],
        "indication": "Peradangan berat, alergi, asma, dan kondisi yang memerlukan terapi steroid singkat.",
        "benefit": "Mengurangi peradangan dan reaksi alergi dengan cepat.",
        "dosage": "0,5-1,5 mg per hari sesuai anjuran dokter, diminum sesudah makan.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "1-2x sehari",
    },
    {
        "match": ["Metilprednisolon", "Methylprednisolone"],
        "indication": "Peradangan dan alergi yang memerlukan terapi steroid.",
        "benefit": "Meredakan peradangan dengan dosis harian sekali di pagi hari.",
        "dosage": "4-48 mg per hari sesuai anjuran dokter, diminum sesudah makan pagi.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Furosemid", "Furosemide"],
        "indication": "Pembengkakan (edema) akibat gagal jantung, gangguan ginjal, dan hipertensi.",
        "benefit": "Membuang kelebihan cairan dan garam lewat urine sehingga bengkak berkurang.",
        "dosage": "20-40 mg diminum di pagi hari sesudah makan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Spironolakton", "Spironolactone"],
        "indication": "Pembengkakan, gagal jantung, dan hipertensi.",
        "benefit": "Membuang kelebihan cairan tanpa banyak menghilangkan kalium.",
        "dosage": "25-100 mg per hari sesuai anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Hidroklorotiazid", "Hydrochlorothiazide"],
        "indication": "Hipertensi dan pembengkakan ringan.",
        "benefit": "Menurunkan tekanan darah dengan mengurangi kadar garam dan cairan tubuh.",
        "dosage": "12,5-25 mg diminum di pagi hari.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Amlodipin", "Amlodipine"],
        "indication": "Hipertensi dan nyeri dada (angina).",
        "benefit": "Melebarkan pembuluh darah sehingga tekanan darah turun dan jantung tidak bekerja berlebihan.",
        "dosage": "5-10 mg per hari.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Losartan"],
        "indication": "Hipertensi dan perlindungan fungsi ginjal pada pasien diabetes.",
        "benefit": "Menurunkan tekanan darah dengan risiko batuk kering lebih kecil dibanding golongan ACE inhibitor.",
        "dosage": "50-100 mg per hari.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Kaptopril", "Captopril"],
        "indication": "Hipertensi dan gagal jantung.",
        "benefit": "Melebarkan pembuluh darah dan menurunkan tekanan darah dengan cepat.",
        "dosage": "12,5-25 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Enalapril"],
        "indication": "Hipertensi dan gagal jantung.",
        "benefit": "Menurunkan tekanan darah dan mengurangi beban kerja jantung.",
        "dosage": "5-20 mg per hari, dapat dibagi menjadi 1-2 dosis.",
        "usage_time": ["pagi", "malam"],
        "frequency": "1-2x sehari",
    },
    {
        "match": ["Atenolol"],
        "indication": "Hipertensi dan penanganan pasca serangan jantung.",
        "benefit": "Memperlambat denyut jantung sehingga tekanan darah lebih stabil.",
        "dosage": "50-100 mg per hari.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Metoprolol"],
        "indication": "Hipertensi, angina, dan gagal jantung.",
        "benefit": "Menurunkan denyut dan tekanan darah, menjaga jantung tetap teratur.",
        "dosage": "25-100 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "malam"],
        "frequency": "1-2x sehari",
    },
    {
        "match": ["Propranolol"],
        "indication": "Hipertensi, tremor, dan rasa gugup berlebihan.",
        "benefit": "Menurunkan denyut jantung serta meredakan tremor dan gugup.",
        "dosage": "20-40 mg per dosis sesudah makan.",
        "usage_time": ["pagi", "siang", "sore", "malam"],
        "frequency": "2-3x sehari",
    },
    {
        "match": ["Simvastatin"],
        "indication": "Kolesterol tinggi dan pencegahan penyakit jantung.",
        "benefit": "Menurunkan kolesterol jahat (LDL) dan lemak darah.",
        "dosage": "10-40 mg diminum di malam hari.",
        "usage_time": ["malam"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Atorvastatin"],
        "indication": "Kolesterol tinggi dan pencegahan stroke.",
        "benefit": "Menurunkan LDL dan menstabilkan lemak darah secara menyeluruh.",
        "dosage": "10-40 mg per hari, dapat diminum kapan saja secara konsisten.",
        "usage_time": ["malam"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Metformin"],
        "indication": "Diabetes melitus tipe 2.",
        "benefit": "Menurunkan gula darah dengan meningkatkan kerja insulin dan mengurangi produksi gula di hati.",
        "dosage": "500 mg per dosis sesudah makan untuk menghindari gangguan lambung.",
        "usage_time": ["pagi", "siang", "malam"],
        "frequency": "2-3x sehari",
    },
    {
        "match": ["Glibenklamid", "Glibenclamide", "Gliklazid", "Gliclazide"],
        "indication": "Diabetes melitus tipe 2.",
        "benefit": "Merangsang pankreas mengeluarkan lebih banyak insulin untuk menurunkan gula darah.",
        "dosage": "Diminum sesudah sarapan pagi sesuai anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Glimepirid", "Glimepiride"],
        "indication": "Diabetes melitus tipe 2.",
        "benefit": "Membantu menurunkan gula darah setelah makan.",
        "dosage": "1-4 mg sesudah sarapan pagi sesuai anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Ferrous Fumarate", "Ferrous Sulfate", "Ferum", "Zat Besi"],
        "indication": "Anemia akibat kekurangan zat besi, terutama pada ibu hamil dan menstruasi.",
        "benefit": "Membantu tubuh membentuk sel darah merah sehingga tidak mudah lemas.",
        "dosage": "1 tablet sesudah makan pagi; hindari teh dan susu 1 jam setelahnya.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Asam Folat", "Folic Acid"],
        "indication": "Pencegahan kekurangan folat, anemia megaloblastik, dan kebutuhan ibu hamil.",
        "benefit": "Mendukung pembentukan sel darah dan perkembangan janin.",
        "dosage": "400-800 mcg per hari sesudah makan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Asam Askorbat", "Vitamin C", "Ascorbic Acid"],
        "indication": "Mencegah dan menangani kekurangan vitamin C.",
        "benefit": "Menjaga daya tahan tubuh dan membantu penyerapan zat besi.",
        "dosage": "500 mg per hari sesudah makan.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Kalsium", "Calcium"],
        "indication": "Pencegahan osteoporosis dan kebutuhan kalsium tambahan.",
        "benefit": "Menjaga kepadatan tulang dan gigi.",
        "dosage": "1 tablet sesudah makan pagi, boleh dengan vitamin D.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Multivitamin", "Vitamin B Kompleks", "Neurobion"],
        "indication": "Pemulihan setelah sakit dan memenuhi kebutuhan vitamin harian.",
        "benefit": "Membantu metabolisme dan menjaga fungsi saraf serta daya tahan tubuh.",
        "dosage": "1 kapsul sesudah makan pagi.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Ketoconazol", "Ketoconazole"],
        "indication": "Infeksi jamur pada kulit, rambut, dan kuku.",
        "benefit": "Membunuh jamur penyebit gatal dan kerontokan akibat infeksi.",
        "dosage": "200 mg per hari sesudah makan, sesuai anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
    {
        "match": ["Klotrimazol", "Clotrimazole"],
        "indication": "Jamur kulit, kurap, kutu air, dan keputihan.",
        "benefit": "Meredakan gatal dan menghilangkan jamur pada area yang dioles.",
        "dosage": "Oleskan tipis dan rata pada area yang terkena, lalu pijat perlahan.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Mikonazol", "Miconazole"],
        "indication": "Infeksi jamur kulit dan ruam popok akibat jamur.",
        "benefit": "Mengurangi gatal, merah, dan perih akibat jamur.",
        "dosage": "Oleskan tipis pada kulit yang terkena setelah dibersihkan.",
        "usage_time": ["pagi", "malam"],
        "frequency": "2x sehari",
    },
    {
        "match": ["Asiklovir", "Acyclovir"],
        "indication": "Infeksi virus herpes dan cacar air.",
        "benefit": "Mempercepat penyembuhan lesi dan mengurangi keluhan nyeri.",
        "dosage": "400 mg per dosis sesudah makan dengan banyak air; umumnya 5-10 hari.",
        "usage_time": ["pagi", "siang", "sore"],
        "frequency": "3x sehari",
    },
    {
        "match": ["Albendazol", "Albendazole"],
        "indication": "Infeksi cacing kait, cacing tambang, dan cacing pita.",
        "benefit": "Membunuh cacing dewasa sehingga gejala akibat infeksi membaik.",
        "dosage": "400 mg dalam satu dosis, diminum di malam hari setelah makan.",
        "usage_time": ["malam"],
        "frequency": "1x (dosis tunggal)",
    },
    {
        "match": ["Klopidogrel", "Clopidogrel"],
        "indication": "Pencegahan penggumpalan darah setelah stroke atau serangan jantung.",
        "benefit": "Menipiskan darah sehingga aliran darah ke jantung dan otak tetap lancar.",
        "dosage": "75 mg per hari sesudah makan, sesuai anjuran dokter.",
        "usage_time": ["pagi"],
        "frequency": "1x sehari",
    },
]


def apply_usage_guides(db) -> int:
    from sqlalchemy import func, or_

    updated = 0
    fields = ("indication", "benefit", "dosage", "usage_time", "frequency")
    for guide in USAGE_GUIDES:
        keys = [key.strip().lower() for key in guide["match"]]
        rows = (
            db.query(Drug)
            .filter(or_(func.lower(Drug.generic_name).in_(keys), func.lower(Drug.name).in_(keys)))
            .all()
        )
        for row in rows:
            changed = False
            for field in fields:
                if not getattr(row, field):
                    setattr(row, field, guide[field])
                    changed = True
            if changed:
                updated += 1
    return updated


def seed():
    db = SessionLocal()
    try:
        existing_names = {name for (name,) in db.query(Drug.name).all()}
        added = 0
        for data in drugs_data:
            if data["name"] not in existing_names:
                data_with_image = {**data, "image_url": get_image_for_category(data.get("category"))}
                db.add(Drug(**data_with_image))
                added += 1
        db.commit()
        print(f"Berhasil menambahkan {added} data obat baru.")
        updated = apply_usage_guides(db)
        db.commit()
        print(f"Berhasil melengkapi aturan pakai pada {updated} obat.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
